const GETTODOLIST = 'GETTODOLIST'
const CHECKSTATUS = 'CHECKSTATUS'
const DELETETASK = 'DELETETASK'
const CHANGENAME = 'CHANGENAME'
const ADDNAME = 'ADDNAME'
const CLEARCOMPLETED = 'CLEARCOMPLETED'
const CHANGETAB = 'CHANGETAB'
const TOGGLEALL = 'TOGGLEALL'

export { GETTODOLIST, CHECKSTATUS, DELETETASK, CHANGENAME, ADDNAME, CLEARCOMPLETED, CHANGETAB, TOGGLEALL }